name: menta-deluged
version: '2.0.3'
summary: Unofficial snap package for deluge daemon
description: |
  This snap package was built to meet a very specific set of requirements. The
  configurations included here may not apply for generic use cases.
base: core18
grade: stable
confinement: strict
architectures: [amd64]

apps:
  deluged:
    command: bin/wrapper.sh
    daemon: simple
    restart-condition: always
    plugs: 
      - network
      - network-bind
      - removable-media

  users:
    command: bin/users.sh

  console:
    command: deluge-console
    plugs: 
      - network

parts:
  deluged:
    source: git://deluge-torrent.org/deluge.git
    source-type: git
    source-tag: deluge-$SNAPCRAFT_PROJECT_VERSION
    plugin: python
    python-version: python3
    stage-packages:
      - intltool
      - python3-libtorrent

  wrapper:
    source: files/
    plugin: dump
    override-build: |
      chmod +x bin/wrapper.sh
      snapcraftctl build
