name: menta-deluged
version: '1.3.12'
summary: Unofficial snap package for deluge daemon
description: |
  This snap package was built to meet a very specific set of requirements. The
  configurations included here may not apply for generic use cases.

apps:

  deluged:
    command: bin/deluged.sh
    daemon: simple
    plugs: [network-bind]

  users:
    command: bin/users.sh

grade: devel
confinement: strict

parts:

  deluged:
    plugin: nil
    stage-packages:
      - deluged=1.3.12-1ubuntu1

  configurations:
    plugin: dump
    source: .
