name: menta-deluged
version: '1.3.12'
summary: Unofficial snap package for deluge daemon
description: |
  This snap package was built to meet a very specific set of requirements. The
  configurations included here may not apply for generic use cases.

apps:

  deluged:
    command: bin/deluged.sh
    daemon: simple
    plugs: [network, network-bind, removable-media]

  users:
    command: bin/users.sh

  console:
    command: deluge-console
    plugs: [network]

grade: devel
confinement: strict

parts:

  deluged:
    source: http://download.deluge-torrent.org/source/deluge-1.3.12.tar.gz
    plugin: python
    python-version: python2
    python-packages:
      - twisted[tls]
      - pyopenssl
      - pillow
      - pyxdg
      - chardet
    stage-packages:
      - intltool
      - python-libtorrent

  configurations:
    plugin: dump
    source: .
